### PR TITLE
Adds env.update_gateway

### PR DESCRIPTION
**Pull request by jimmybaker**

### CODE REVIEW

**Comment by duff** [comment]
Looks like a duplicate of https://github.com/spreedly/spreedly-gem/pull/38

Anything different code wise between the two?

**Comment by jimmybaker** [comment]
Yeah, this one works. #38 doesn't due to the called to add_to_doc which I guess has been refactored since #38 was opened. Sorry I should've explained this when I opened the PR.

**Comment by jimmybaker** [comment]
Can we reopen this and possibly merge it?

**Comment by duff** [comment]
I've added it to my list to look at this again.

**Pull request closed without merging**
