### PR TITLE
Add support for offsite gateways

### PR DESCRIPTION
**Pull request by joeybeninghove**
This is to add support for the offsite gateways.  I included a bunch of unit and remote tests using the Sprel gateway as well.  Let me know what you guys think and if I missed anything!

### CODE REVIEW

**Comment by kieranklaassen** [comment]
I need this! Nice. Thanks

**Comment by pelletencate** [comment]
+1 just following you @kieranklaassen, great catch. I need this too! Thanks @joeybeninghove

**Comment by ericdisilvestro** [comment]
+1

**Comment by aksh0925** [comment]
+1 mee two.

**Comment by nchytry** [comment]
+1 samesies

**Comment by kieranklaassen** [comment]
Will this be in at some point? I am still using my own version of the gem.

**Comment by kieranklaassen** [comment]
Any updates on this?

**Comment by duff** [comment]
No updates yet.  Still on our list.

**Comment by jeremywrowe** [comment]
@joeybeninghove If you can bring this up to date with master I'd be happy to review it for you.

**Comment by jeremywrowe** [comment]
Closing this due to no response. Please feel free to reopen though 😄

**Pull request closed without merging**
