### PR TITLE
Add ability to update gateway

### PR DESCRIPTION
**Pull request by Maysora**
related to https://github.com/spreedly/spreedly-gem/issues/10

lacking remote test though..

### CODE REVIEW

**Comment by cheezy2022** [comment]
:+1:

**Comment by jimmybaker** [comment]
Can we merge this or what?

**Comment by jeremywrowe** [comment]
@Maysora This is a long shot, but would you mind bringing this up to date with master and pinging me? I'll be happy to review it after.

**Comment by jeremywrowe** [comment]
Closing due to no response. Please feel free to reopen though. 🎉

**Pull request closed without merging**
